# Generated by Django 4.2.16 on 2024-12-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teffyapp.personalinformation')),
            ],
        ),
    ]
