# Generated by Django 4.2.16 on 2024-12-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
