# Generated by Django 4.2.16 on 2024-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0004_remove_personalinformation_programe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
