# Generated by Django 4.2.16 on 2024-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0005_personalinformation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermangament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_group', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
