# Generated by Django 4.2.16 on 2024-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0006_usermangament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangament',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usermangament',
            name='user_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
