# Generated by Django 4.2.16 on 2024-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0007_alter_usermangament_date_alter_usermangament_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangament',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
