# Generated by Django 4.2.16 on 2024-12-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0008_alter_usermangament_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermangament',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
