# Generated by Django 4.2.16 on 2024-12-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0009_alter_usermangament_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermangament',
            table='usermangament',
        ),
    ]
