# Generated by Django 4.2.16 on 2024-12-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0010_alter_usermangament_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermangament',
            table=None,
        ),
    ]
