# Generated by Django 4.2.16 on 2024-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
