# Generated by Django 4.2.16 on 2025-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0017_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='services',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
