# Generated by Django 4.2.16 on 2025-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0019_service_remove_personalinformation_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='services',
            field=models.ManyToManyField(blank=True, to='teffyapp.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
