# Generated by Django 4.2.16 on 2025-01-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0020_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='prices',
        ),
    ]
