# Generated by Django 4.2.16 on 2025-01-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0024_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('pending_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_mode', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('payements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teffyapp.personalinformation')),
            ],
        ),
    ]
