# Generated by Django 4.2.16 on 2025-01-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0025_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payements',
            new_name='payments',
        ),
    ]
