# Generated by Django 4.2.16 on 2025-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0026_rename_payements_payments_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
