# Generated by Django 4.2.16 on 2025-01-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0027_alter_payments_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_records', to='teffyapp.personalinformation'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='teffyapp.personalinformation'),
        ),
    ]
