# Generated by Django 4.2.16 on 2025-01-09 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0028_payments_name_alter_payments_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
