# Generated by Django 4.2.16 on 2025-01-09 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0029_payments_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_spent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
