# Generated by Django 4.2.16 on 2025-01-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0030_expense_date_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
