# Generated by Django 4.2.16 on 2025-01-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0033_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
