# Generated by Django 4.2.16 on 2025-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0034_alter_returns_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
