# Generated by Django 4.2.16 on 2025-01-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0035_sales_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
