# Generated by Django 4.2.16 on 2025-01-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0036_sales_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returns',
            old_name='return_reason',
            new_name='reason',
        ),
    ]
