# Generated by Django 4.2.16 on 2025-01-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0038_returns_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
