# Generated by Django 4.2.16 on 2025-01-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0039_alter_returns_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
