# Generated by Django 4.2.16 on 2025-01-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0041_report_personalinformation_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teffyapp.personalinformation'),
        ),
    ]
