# Generated by Django 4.2.16 on 2025-01-22 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0042_remove_personalinformation_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='follow_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
