# Generated by Django 4.2.16 on 2025-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0044_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renew',
            name='renew_date',
            field=models.DateField(),
        ),
    ]
