# Generated by Django 4.2.16 on 2025-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0045_alter_renew_renew_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='services',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='services',
            field=models.ManyToManyField(related_name='users', to='teffyapp.service'),
        ),
    ]
