# Generated by Django 4.2.16 on 2025-01-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0046_remove_personalinformation_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='services',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='teffyapp.service'),
        ),
    ]
