# Generated by Django 4.2.16 on 2025-01-24 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0047_remove_personalinformation_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
