# Generated by Django 4.2.16 on 2025-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0048_personalinformation_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
