# Generated by Django 4.2.16 on 2025-01-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0049_personalinformation_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='renew',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
