# Generated by Django 4.2.16 on 2025-01-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0051_purchase_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
    ]
