# Generated by Django 4.2.16 on 2025-01-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0054_alter_sales_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
