# Generated by Django 4.2.16 on 2025-01-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0055_alter_purchase_purchase_date_alter_sales_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
    ]
