# Generated by Django 4.2.16 on 2025-01-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0057_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
