# Generated by Django 4.2.16 on 2025-01-25 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0058_alter_sales_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_spent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
