# Generated by Django 4.2.16 on 2025-01-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0059_alter_expense_date_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='renew',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
