# Generated by Django 4.2.16 on 2025-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0060_renew_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
