# Generated by Django 4.2.16 on 2025-01-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0061_service_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('country_code', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_number', models.CharField(blank=True, max_length=15, null=True)),
                ('reg_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prices', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sessions', models.PositiveIntegerField()),
                ('discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conveniance_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enrollment_date', models.DateField()),
                ('activation_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('current_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_by_cash', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='member_files/')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_with_group', to='teffyapp.service')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_with_package', to='teffyapp.service')),
            ],
        ),
    ]
