# Generated by Django 4.2.16 on 2025-01-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0063_rename_sold_by_addmember_sold_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmember',
            old_name='discount_type',
            new_name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='current_installment',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='package',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='paid_by_cash',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='reg_amount',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='sold_By',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='total_sessions',
        ),
        migrations.AddField(
            model_name='addmember',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_members', to='teffyapp.service'),
        ),
        migrations.AddField(
            model_name='addmember',
            name='cost_of_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_of_plan_members', to='teffyapp.service'),
        ),
        migrations.AddField(
            model_name='addmember',
            name='current_installment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='registration_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_members', to='teffyapp.service'),
        ),
        migrations.AddField(
            model_name='addmember',
            name='total_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_session_members', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='aadhar_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='conveniance_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='sold_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
