# Generated by Django 4.2.16 on 2025-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0064_rename_discount_type_addmember_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
