# Generated by Django 4.2.16 on 2025-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0065_alter_addmember_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sessions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
