# Generated by Django 4.2.16 on 2025-01-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0066_service_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='discount_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_by_batch', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='cost_of_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_by_cost', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_by_service', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='total_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_by_session', to='teffyapp.service'),
        ),
    ]
