# Generated by Django 4.2.16 on 2025-01-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0067_addmember_discount_addmember_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_members', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='cost_of_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_of_plan_members', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='total_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_session_members', to='teffyapp.service'),
        ),
    ]
