# Generated by Django 4.2.16 on 2025-01-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0068_alter_addmember_batch_alter_addmember_cost_of_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmember',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teffyapp.userprofile'),
        ),
    ]
