# Generated by Django 4.2.16 on 2025-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0069_alter_addmember_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
