# Generated by Django 4.2.16 on 2025-02-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0070_expense_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='expiry_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_expiry_date', to='teffyapp.service'),
        ),
    ]
