# Generated by Django 4.2.16 on 2025-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0072_remove_personalinformation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
