# Generated by Django 4.2.16 on 2025-02-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0074_remove_personalinformation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='plan_leads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_leads', to='teffyapp.plan'),
        ),
    ]
