# Generated by Django 4.2.16 on 2025-02-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0075_personalinformation_plan_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='renewal_date',
        ),
    ]
