# Generated by Django 4.2.16 on 2025-02-07 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0076_remove_personalinformation_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
