# Generated by Django 4.2.16 on 2025-02-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0077_personalinformation_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='select_membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teffyapp.plan'),
        ),
    ]
