# Generated by Django 4.2.16 on 2025-02-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0078_addmember_select_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='expiry_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teffyapp.service'),
        ),
    ]
