# Generated by Django 4.2.16 on 2025-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0079_personalinformation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
