# Generated by Django 4.2.16 on 2025-02-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0082_remove_addmember_location_addmember_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='addmember',
            name='status',
        ),
        migrations.AddField(
            model_name='addmember',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='aadhar_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='select_membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teffyapp.plan'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_by_service', to='teffyapp.service'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='teffyapp.service'),
        ),
    ]
