# Generated by Django 4.2.16 on 2025-02-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0084_personalinformation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='converted_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='teffyapp.addmember'),
        ),
    ]
