# Generated by Django 4.2.16 on 2025-02-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0085_personalinformation_conversion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='conversion_date',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='converted_member',
        ),
    ]
