# Generated by Django 4.2.16 on 2025-02-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0086_remove_personalinformation_conversion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addmember',
            name='converted_from_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_members', to='teffyapp.personalinformation'),
        ),
    ]
