# Generated by Django 4.2.16 on 2025-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0091_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
