# Generated by Django 4.2.16 on 2025-02-19 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0092_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(default=0)),
                ('pending_amount', models.FloatField(default=0)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online Transfer', 'Online Transfer')], max_length=50)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='teffyapp.addmember')),
            ],
        ),
    ]
