# Generated by Django 4.2.16 on 2025-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0093_memberpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
