# Generated by Django 4.2.16 on 2025-02-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0094_alter_plan_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='batches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='teffyapp.plan'),
        ),
        migrations.AlterField(
            model_name='addmember',
            name='select_membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teffyapp.plan'),
        ),
    ]
