# Generated by Django 4.2.16 on 2025-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0095_addmember_batches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
