# Generated by Django 4.2.16 on 2025-02-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0096_personalinformation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmember',
            name='converted_from_lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_conversion', to='teffyapp.personalinformation'),
        ),
        migrations.AddField(
            model_name='addmember',
            name='member_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='converted_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='teffyapp.addmember'),
        ),
    ]
