# Generated by Django 4.2.16 on 2025-03-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0097_addmember_converted_from_lead_addmember_member_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
