# Generated by Django 4.2.16 on 2025-03-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0099_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmember',
            name='converted_from_lead',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='converted_member',
        ),
    ]
