# Generated by Django 4.2.16 on 2025-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0100_remove_addmember_converted_from_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
