# Generated by Django 4.2.16 on 2025-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0101_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenumber',
            name='current_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
