# Generated by Django 4.2.15 on 2025-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teffyapp', '0102_alter_invoicenumber_current_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenumber',
            name='current_number',
            field=models.IntegerField(default=1),
        ),
    ]
